### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module in Next.js

### ISSUE THREAD

**Issue by HediMuhamad** [viclafouch/mui-otp-input#31]
#### How to reproduce
- Initiate Next.js project with `npx create-next-app@latest`
- Install MUI `yarn add @mui/material @emotion/react @emotion/styled`
- Install the library with `yarn add mui-one-time-password-input`
- Run `yarn dev`

#### Error message
```
- error /home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/mui-one-time-password-input/dist/mui-one-time-password-input.es.js:1
import { jsx as E } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.mui-one-time-password-input (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:194:18)
    at __webpack_require__ (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index.tsx:11:85)
    at Object../src/pages/index.tsx (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:97:1)
    at __webpack_require__ (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES&page=%2F&preferredRegion=&absolutePagePath=.%2Fsrc%2Fpages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D!:22:78)
    at Object../node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES&page=%2F&preferredRegion=&absolutePagePath=.%2Fsrc%2Fpages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D! (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:53:1)
    at __webpack_require__ (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:314:39)
    at /home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:315:28
    at Object.<anonymous> (/home/hedi/Repositories/mui-one-time-password-next-canary/.next/server/pages/index.js:318:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requirePage (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/require.js:112:75)
    at /home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/load-components.js:80:84
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadComponentsImpl (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/load-components.js:80:26)
    at async DevServer.findPageComponentsImpl (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/next-server.js:434:36)
    at async DevServer.findPageComponents (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/dev/next-dev-server.js:563:20)
    at async DevServer.renderPageComponent (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/base-server.js:1430:24)
    at async DevServer.renderToResponseImpl (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/base-server.js:1486:32)
    at async DevServer.pipeImpl (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/base-server.js:727:25)
    at async DevServer.handleCatchallRenderRequest (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/next-server.js:698:13)
    at async DevServer.handleRequestImpl (/home/hedi/Repositories/mui-one-time-password-next-canary/node_modules/next/dist/server/base-server.js:639:17) {
  digest: undefined
}
```

**Comment by viclafouch** [comment]
Hello !

Try this :

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['mui-one-time-password-input'],
}
 
module.exports = nextConfig
```

**Comment by HediMuhamad** [comment]
Oh, It's un-transpiled package,
Thanks for the fast response.

**Comment by zolzaya** [comment]
I have a same issue on Remix. I'm using 2.0 how can I fix it in Remix?

**Comment by enahs** [comment]
This doesn't work in next.

> Hello !
> 
> Try this :
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   transpilePackages: ['mui-one-time-password-input'],
> }
>  
> module.exports = nextConfig
> ```

Doesn't work for next.js 12

**Comment by viclafouch** [comment]
For next 12, use this plugin : https://github.com/martpie/next-transpile-modules/
