### ISSUE TITLE
Doesn't work with react 16

### ISSUE THREAD

**Issue by artemijan** [viclafouch/mui-otp-input#35]
I'm trying to use this input with react 16, and I see this error in console, page is broken
`
Uncaught TypeError: Cannot read properties of null (reading 'useRef')
    at Object.useRef (react.development.js:1630:1)
    at mui-one-time-password-input.es.js:76:16
    at renderWithHooks (react-dom.development.js:14803:1)
    at updateForwardRef (react-dom.development.js:16816:1)
    at beginWork (react-dom.development.js:18645:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)
`

**Comment by viclafouch** [comment]
Only with React 18, sorry
