### ISSUE TITLE
Error react/jsx-runtime Next.js

### ISSUE THREAD

**Issue by Victor1890** [viclafouch/mui-otp-input#41]
Hi!, I found a problem when I tried to use this library

```sh
project\node_modules\mui-one-time-password-input\dist\mui-one-time-password-input.es.js:1
import { jsx as E } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at mui-one-time-password-input (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:2104:18)
    at __webpack_require__ (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/app/code/AuthCodeVerification.tsx:11:85)
    at ./components/app/code/AuthCodeVerification.tsx (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:125:1)
    at __webpack_require__ (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/app/extended/CodeVerification.tsx:12:84)
    at __webpack_require__.a (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/app/extended/CodeVerification.tsx:1:21)
    at ./components/app/extended/CodeVerification.tsx (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:147:1)
    at __webpack_require__ (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:28:100)
    at __webpack_require__.a (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/_app.tsx:1:21)
    at ./pages/_app.tsx (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:268:1)
    at __webpack_require__ (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:2257:39)
    at D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:2258:28
    at Object.<anonymous> (D:\workspaces\freelance\integra\integra-frontend-v2\.next\server\pages\_app.js:2261:3)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (D:\workspaces\freelance\integra\integra-frontend-v2\node_modules\next\dist\server\require.js:88:12)
    at D:\workspaces\freelance\integra\integra-frontend-v2\node_modules\next\dist\server\load-components.js:46:54
    at async Promise.all (index 1)
    at async Object.loadComponentsImpl [as loadComponents] (D:\workspaces\freelance\integra\integra-frontend-v2\node_modules\next\dist\server\load-components.js:44:33)
    at async DevServer.findPageComponentsImpl (D:\workspaces\freelance\integra\integra-frontend-v2\node_modules\next\dist\server\next-server.js:600:36) {
  page: '/'
}
```
![image](https://github.com/viclafouch/mui-otp-input/assets/46900196/10c9db6d-244a-41e0-aba6-96136c81febb)

Dependency | Version
-- | --
Operating System | Windows 11
Node.js version | 18.14.0
Typescript version | 4.9.4
Next.js version | 13.2.4
"react" | 18.2.0
"mui/material" | 5.11.3
"mui-one-time-password-input" | 2.0.0

**Comment by viclafouch** [comment]
Duplicate with https://github.com/viclafouch/mui-otp-input/issues/31
