### ISSUE TITLE
Bug Report: `SyntaxError: Cannot use import statement outside a module` with `mui-one-time-password-input`

### ISSUE THREAD

**Issue by parsaM110** [viclafouch/mui-otp-input#62]
I recently encountered a sudden and unexpected issue with my Next.js project. Previously, everything was functioning smoothly, but now I'm getting the following error:

```
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/Users/vincent/projects/ticket-app/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at mui-one-time-password-input (/Users/vincent/projects/ticket-app/.next/server/pages/_app.js:611:18)
    at __webpack_require__ (/Users/vincent/projects/ticket-app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/layout/header/Dialog.js:34:86)
    at __webpack_require__.a (/Users/vincent/projects/ticket-app/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/components/layout/header/Dialog.js:1:21)
    at ./src/components/layout/header/Dialog.js (/Users/vincent/projects/ticket-app/.next/server/pages/_app.js:62:1) {
  page: '/'
}
```

**Environment:**
- **Node.js version:** v20.11.0
- **Next.js version:** 14.2.4
- **mui-one-time-password-input version:** 2.0.2

**Steps to Reproduce:**
1. Clone the repository (link to your repository, if public).
2. Install dependencies using `npm install`.
3. Start the development server using `npm run dev`.

**Expected Behavior:**
The application should start without any syntax errors, and the `mui-one-time-password-input` component should work as expected.

**Actual Behavior:**
The application fails to start with the `SyntaxError: Cannot use import statement outside a module` error, specifically related to the `mui-one-time-password-input` package.

**Additional Context:**

Here is my `package.json` for reference:

```json
{
  "name": "ticket-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/cache": "^11.11.0",
    "@emotion/react": "^11.11.4",
    "@emotion/server": "^11.11.0",
    "@emotion/styled": "^11.11.5",
    "@mui/icons-material": "^5.15.20",
    "@mui/lab": "^5.0.0-alpha.170",
    "@mui/material": "^5.15.20",
    "@mui/material-nextjs": "^5.15.11",
    "axios": "^1.7.2",
    "mui-one-time-password-input": "^2.0.2",
    "next": "14.2.4",
    "notistack": "^3.0.1",
    "react": "^18",
    "react-dom": "^18",
    "react-slick": "^0.30.2",
    "slick-carousel": "^1.8.1"
  }
}
```

**What I've Tried:**
- Reinstalling node modules.
- Clearing cache and rebuilding the project.
- Verifying the `next.config.js` settings (if applicable).

Any insights or suggestions on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by hannahlaek-wt** [comment]
Same thing happening to me in my next js project as well as errors like to match issue #59 
'ConfirmModal' cannot be used as a JSX component.
  Its type 'FC<ConfirmModalProps> & ConfirmModalCompoundComponents' is not a valid JSX element type.
    Type 'FC<ConfirmModalProps> & ConfirmModalCompoundComponents' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, any>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, any>' but required in type 'ReactPortal'.ts(2786)

**Comment by viclafouch** [comment]
Hello ! 

Try this in your next config file : 

```ts
const nextConfig = {
  transpilePackages: ['mui-one-time-password-input'],
}
```

**Comment by thecodeinfluencer** [comment]
If you're still experiencing this issue, try these fixes (fix 1 worked for me):

1. Upgrade your `@types/react` in `devDependencies` to `18.2.25` (mine was initially`18.2.0`):

```
"devDependencies": {
    ...
    "@types/react": "18.2.25",
    ...
  },
```

2. Try [clearing your VS Code cache](https://bobbyhadz.com/blog/vscode-clear-cache)
